/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: U235 (https://sketchfab.com/u235)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/animated-atom-blender-cycles-e1fe282c45664713bf5f7e000b6e90d4
Title: Animated Atom "blender cycles"
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/scene.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Sphere_2"
                position={[0, -2.038, 0]}
                rotation={[0.559, 0, 0]}
                scale={0.169}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Icosphere_83" position={[0, -2.038, 0]} scale={0.945}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials['Material.001']}
                />
                <group
                  name="Sphere052_3"
                  position={[0.083, -0.901, 0.27]}
                  rotation={[-2.843, 0.651, -0.138]}
                  scale={0.179}>
                  <mesh
                    name="Object_8"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_8.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere053_4"
                  position={[0.659, -0.6, 0.253]}
                  rotation={[0.683, -0.418, -2.233]}
                  scale={0.179}>
                  <mesh
                    name="Object_10"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_10.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere062_5"
                  position={[-0.238, -0.903, 0.167]}
                  rotation={[1.054, 1.177, 2.374]}
                  scale={0.179}>
                  <mesh
                    name="Object_12"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_12.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere063_6"
                  position={[-0.232, -0.907, -0.176]}
                  rotation={[0.751, -0.082, 2.882]}
                  scale={0.179}>
                  <mesh
                    name="Object_14"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_14.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere064_7"
                  position={[0.091, -0.897, -0.286]}
                  rotation={[1.402, -1.295, -2.593]}
                  scale={0.179}>
                  <mesh
                    name="Object_16"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_16.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere065_8"
                  position={[0.839, -0.322, 0.258]}
                  rotation={[2.163, -0.407, -1.291]}
                  scale={0.179}>
                  <mesh
                    name="Object_18"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_18.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere066_9"
                  position={[-0.021, -0.32, 0.873]}
                  rotation={[2.419, -0.126, 0.043]}
                  scale={0.179}>
                  <mesh
                    name="Object_20"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_20.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere067_10"
                  position={[-0.83, -0.329, 0.283]}
                  rotation={[2.442, 0.279, 1.154]}
                  scale={0.179}>
                  <mesh
                    name="Object_22"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_22.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere068_11"
                  position={[-0.512, -0.326, -0.708]}
                  rotation={[1.91, 0.372, 2.563]}
                  scale={0.179}>
                  <mesh
                    name="Object_24"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_24.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere069_12"
                  position={[0.544, -0.323, -0.717]}
                  rotation={[1.833, -0.131, -2.638]}
                  scale={0.179}>
                  <mesh
                    name="Object_26"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_26.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere070_13"
                  position={[0.754, -0.161, 0.534]}
                  rotation={[3.09, 0.434, -1.038]}
                  scale={0.179}>
                  <mesh
                    name="Object_28"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_28.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere071_14"
                  position={[-0.297, -0.157, 0.862]}
                  rotation={[1.811, 0.937, 0.53]}
                  scale={0.179}>
                  <mesh
                    name="Object_30"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_30.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere072_15"
                  position={[-0.933, -0.148, 0.006]}
                  rotation={[1.106, 0.127, 1.732]}
                  scale={0.179}>
                  <mesh
                    name="Object_32"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_32.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere073_16"
                  position={[-0.271, -0.147, -0.889]}
                  rotation={[1.553, -0.792, 2.672]}
                  scale={0.179}>
                  <mesh
                    name="Object_34"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_34.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere074_17"
                  position={[0.759, -0.153, -0.555]}
                  rotation={[3.002, -0.52, -1.902]}
                  scale={0.179}>
                  <mesh
                    name="Object_36"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_36.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere075_18"
                  position={[0.385, 0.633, 0.619]}
                  rotation={[1.591, 0.588, -0.523]}
                  scale={0.179}>
                  <mesh
                    name="Object_38"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_38.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere076_19"
                  position={[-0.475, 0.602, 0.559]}
                  rotation={[1.444, -0.322, 0.547]}
                  scale={0.179}>
                  <mesh
                    name="Object_40"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_40.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere077_20"
                  position={[-0.677, 0.596, -0.275]}
                  rotation={[2.109, -0.771, 1.866]}
                  scale={0.179}>
                  <mesh
                    name="Object_42"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_42.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere078_21"
                  position={[0.056, 0.606, -0.712]}
                  rotation={[2.831, -0.144, -3.135]}
                  scale={0.179}>
                  <mesh
                    name="Object_44"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_44.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere079_22"
                  position={[0.698, 0.617, -0.191]}
                  rotation={[2.588, 0.587, -2.059]}
                  scale={0.179}>
                  <mesh
                    name="Object_46"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_46.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere080_23"
                  position={[0.227, 0.908, -0.176]}
                  rotation={[-3.109, 0.857, -2.753]}
                  scale={0.179}>
                  <mesh
                    name="Object_48"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_48.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere081_24"
                  position={[0.457, 0.75, -0.344]}
                  rotation={[1.109, 1.001, -1.078]}
                  scale={0.179}>
                  <mesh
                    name="Object_50"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_50.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere082_25"
                  position={[0.373, 0.612, -0.617]}
                  rotation={[2.67, 0.534, -2.667]}
                  scale={0.179}>
                  <mesh
                    name="Object_52"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_52.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere083_26"
                  position={[-0.1, 0.895, -0.262]}
                  rotation={[-2.994, -0.31, 2.968]}
                  scale={0.179}>
                  <mesh
                    name="Object_54"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_54.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere084_27"
                  position={[-0.188, 0.731, -0.525]}
                  rotation={[-2.976, 0.742, 2.811]}
                  scale={0.179}>
                  <mesh
                    name="Object_56"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_56.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere085_28"
                  position={[-0.485, 0.587, -0.535]}
                  rotation={[2.878, -0.22, 2.65]}
                  scale={0.179}>
                  <mesh
                    name="Object_58"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_58.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere086_29"
                  position={[-0.293, 0.895, 0.009]}
                  rotation={[1.949, -1.187, 1.42]}
                  scale={0.179}>
                  <mesh
                    name="Object_60"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_60.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere087_30"
                  position={[-0.573, 0.739, 0.007]}
                  rotation={[-2.899, -0.406, 2.451]}
                  scale={0.179}>
                  <mesh
                    name="Object_62"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_62.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere088_31"
                  position={[-0.661, 0.613, 0.278]}
                  rotation={[2.078, -0.753, 1.247]}
                  scale={0.179}>
                  <mesh
                    name="Object_64"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_64.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere089_32"
                  position={[-0.079, 0.907, 0.268]}
                  rotation={[0.924, -0.27, 0.121]}
                  scale={0.179}>
                  <mesh
                    name="Object_66"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_66.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere090_33"
                  position={[-0.173, 0.74, 0.546]}
                  rotation={[1.896, -1.289, 0.742]}
                  scale={0.179}>
                  <mesh
                    name="Object_68"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_68.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere091_34"
                  position={[0.066, 0.616, 0.729]}
                  rotation={[1.371, -0.065, -0.009]}
                  scale={0.179}>
                  <mesh
                    name="Object_70"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_70.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere092_35"
                  position={[0.238, 0.912, 0.158]}
                  rotation={[1.107, 0.917, -0.446]}
                  scale={0.179}>
                  <mesh
                    name="Object_72"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_72.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere093_36"
                  position={[0.463, 0.762, 0.327]}
                  rotation={[0.838, -0.194, -0.532]}
                  scale={0.179}>
                  <mesh
                    name="Object_74"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_74.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere094_37"
                  position={[0.694, 0.626, 0.147]}
                  rotation={[1.683, 0.589, -1.129]}
                  scale={0.179}>
                  <mesh
                    name="Object_76"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_76.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere095_38"
                  position={[0.835, 0.335, -0.288]}
                  rotation={[-3.028, -0.179, -2.01]}
                  scale={0.179}>
                  <mesh
                    name="Object_78"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_78.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere096_39"
                  position={[0.737, 0.183, -0.545]}
                  rotation={[2.205, 0.17, -2.189]}
                  scale={0.179}>
                  <mesh
                    name="Object_80"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_80.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere097_40"
                  position={[0.517, 0.328, -0.721]}
                  rotation={[3.088, -0.66, -2.364]}
                  scale={0.179}>
                  <mesh
                    name="Object_82"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_82.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere098_41"
                  position={[0.009, 0.324, -0.885]}
                  rotation={[2.471, -1.094, 3.064]}
                  scale={0.179}>
                  <mesh
                    name="Object_84"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_84.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere099_42"
                  position={[-0.277, 0.168, -0.876]}
                  rotation={[2.36, -0.046, 2.804]}
                  scale={0.179}>
                  <mesh
                    name="Object_86"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_86.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere100_43"
                  position={[-0.528, 0.306, -0.713]}
                  rotation={[1.545, -0.951, 2.072]}
                  scale={0.179}>
                  <mesh
                    name="Object_88"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_88.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere101_44"
                  position={[-0.85, 0.322, -0.288]}
                  rotation={[0.991, -0.433, 1.35]}
                  scale={0.179}>
                  <mesh
                    name="Object_90"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_90.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere102_45"
                  position={[-0.925, 0.18, -0.007]}
                  rotation={[2.145, -0.212, 1.542]}
                  scale={0.179}>
                  <mesh
                    name="Object_92"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_92.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere103_46"
                  position={[-0.839, 0.327, 0.277]}
                  rotation={[1.06, 0.09, 1.128]}
                  scale={0.179}>
                  <mesh
                    name="Object_94"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_94.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere104_47"
                  position={[-0.521, 0.31, 0.72]}
                  rotation={[1.111, 0.741, 0.915]}
                  scale={0.179}>
                  <mesh
                    name="Object_96"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_96.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere105_48"
                  position={[-0.294, 0.159, 0.864]}
                  rotation={[2.038, 0.003, 0.311]}
                  scale={0.179}>
                  <mesh
                    name="Object_98"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_98.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere106_49"
                  position={[-0.009, 0.327, 0.885]}
                  rotation={[1.859, 0.986, 0.044]}
                  scale={0.179}>
                  <mesh
                    name="Object_100"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_100.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere107_50"
                  position={[0.519, 0.343, 0.722]}
                  rotation={[3.069, 0.889, -1.378]}
                  scale={0.179}>
                  <mesh
                    name="Object_102"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_102.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere108_51"
                  position={[0.739, 0.177, 0.542]}
                  rotation={[1.999, 0.151, -0.921]}
                  scale={0.179}>
                  <mesh
                    name="Object_104"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_104.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere109_52"
                  position={[0.836, 0.331, 0.259]}
                  rotation={[3.106, 0.446, -1.707]}
                  scale={0.179}>
                  <mesh
                    name="Object_106"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_106.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere110_53"
                  position={[0.295, 0.151, -0.893]}
                  rotation={[2.307, 0.051, -2.791]}
                  scale={0.179}>
                  <mesh
                    name="Object_108"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_108.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere111_54"
                  position={[0.301, -0.163, -0.879]}
                  rotation={[1.408, 0.909, -2.567]}
                  scale={0.179}>
                  <mesh
                    name="Object_110"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_110.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere112_55"
                  position={[0.021, -0.305, -0.884]}
                  rotation={[1.705, -0.128, -3.135]}
                  scale={0.179}>
                  <mesh
                    name="Object_112"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_112.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere113_56"
                  position={[-0.762, 0.136, -0.556]}
                  rotation={[2.182, -0.123, 2.247]}
                  scale={0.179}>
                  <mesh
                    name="Object_114"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_114.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere114_57"
                  position={[-0.753, -0.181, -0.538]}
                  rotation={[2.977, 0.65, 1.819]}
                  scale={0.179}>
                  <mesh
                    name="Object_116"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_116.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere115_58"
                  position={[-0.849, -0.323, -0.257]}
                  rotation={[1.848, 0.324, 1.899]}
                  scale={0.179}>
                  <mesh
                    name="Object_118"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_118.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere116_59"
                  position={[-0.743, 0.138, 0.545]}
                  rotation={[2.091, -0.091, 0.886]}
                  scale={0.179}>
                  <mesh
                    name="Object_120"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_120.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere117_60"
                  position={[-0.726, -0.189, 0.538]}
                  rotation={[3.072, -0.47, 1.034]}
                  scale={0.179}>
                  <mesh
                    name="Object_122"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_122.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere118_61"
                  position={[-0.508, -0.333, 0.71]}
                  rotation={[2.246, 0.354, 0.662]}
                  scale={0.179}>
                  <mesh
                    name="Object_124"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_124.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere119_62"
                  position={[0.285, 0.154, 0.874]}
                  rotation={[2.084, 0.008, -0.251]}
                  scale={0.179}>
                  <mesh
                    name="Object_126"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_126.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere120_63"
                  position={[0.277, -0.177, 0.865]}
                  rotation={[1.854, -0.978, -0.457]}
                  scale={0.179}>
                  <mesh
                    name="Object_128"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_128.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere121_64"
                  position={[0.526, -0.326, 0.705]}
                  rotation={[2.477, -0.138, -0.658]}
                  scale={0.179}>
                  <mesh
                    name="Object_130"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_130.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere122_65"
                  position={[0.926, 0.151, -0.014]}
                  rotation={[2.191, 0.137, -1.601]}
                  scale={0.179}>
                  <mesh
                    name="Object_132"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_132.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere123_66"
                  position={[0.914, -0.165, -0.007]}
                  rotation={[1.163, -0.079, -1.755]}
                  scale={0.179}>
                  <mesh
                    name="Object_134"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_134.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere124_67"
                  position={[0.845, -0.317, -0.292]}
                  rotation={[2.113, -0.279, -1.767]}
                  scale={0.179}>
                  <mesh
                    name="Object_136"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_136.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere125_68"
                  position={[0.489, -0.599, -0.559]}
                  rotation={[2.282, -1.12, -2.099]}
                  scale={0.179}>
                  <mesh
                    name="Object_138"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_138.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere126_69"
                  position={[0.192, -0.726, -0.554]}
                  rotation={[1.3, -0.207, -2.898]}
                  scale={0.179}>
                  <mesh
                    name="Object_140"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_140.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere127_70"
                  position={[-0.032, -0.592, -0.717]}
                  rotation={[1.41, -1.365, 3.047]}
                  scale={0.179}>
                  <mesh
                    name="Object_142"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_142.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere128_71"
                  position={[-0.365, -0.606, -0.612]}
                  rotation={[1.278, -0.31, 2.712]}
                  scale={0.179}>
                  <mesh
                    name="Object_144"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_144.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere129_72"
                  position={[-0.464, -0.749, -0.338]}
                  rotation={[1.46, 0.67, 2.481]}
                  scale={0.179}>
                  <mesh
                    name="Object_146"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_146.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere130_73"
                  position={[-0.707, -0.611, -0.153]}
                  rotation={[0.712, -0.073, 2.235]}
                  scale={0.179}>
                  <mesh
                    name="Object_148"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_148.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere131_74"
                  position={[-0.694, -0.612, 0.177]}
                  rotation={[1.421, 0.671, 1.816]}
                  scale={0.179}>
                  <mesh
                    name="Object_150"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere132_75"
                  position={[-0.457, -0.747, 0.335]}
                  rotation={[2.782, 0.692, 0.673]}
                  scale={0.179}>
                  <mesh
                    name="Object_152"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_152.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere133_76"
                  position={[-0.375, -0.607, 0.613]}
                  rotation={[0.69, 1.081, 2.164]}
                  scale={0.179}>
                  <mesh
                    name="Object_154"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere134_77"
                  position={[0.673, -0.6, -0.301]}
                  rotation={[1.045, -0.279, -2.354]}
                  scale={0.179}>
                  <mesh
                    name="Object_156"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere135_78"
                  position={[0.562, -0.725, -0.021]}
                  rotation={[0.222, 0.413, -2.385]}
                  scale={0.179}>
                  <mesh
                    name="Object_158"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere136_79"
                  position={[0.277, -0.896, -0.011]}
                  rotation={[0.812, -0.524, -2.714]}
                  scale={0.179}>
                  <mesh
                    name="Object_160"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_160.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere137_80"
                  position={[-0.063, -0.599, 0.719]}
                  rotation={[2.727, 0.816, 0.131]}
                  scale={0.179}>
                  <mesh
                    name="Object_162"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_162.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere138_81"
                  position={[0.176, -0.737, 0.544]}
                  rotation={[3.032, -0.274, -0.2]}
                  scale={0.179}>
                  <mesh
                    name="Object_164"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_164.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group
                  name="Sphere139_82"
                  position={[0.467, -0.607, 0.538]}
                  rotation={[-2.756, 0.696, -0.749]}
                  scale={0.179}>
                  <mesh
                    name="Object_166"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_166.geometry}
                    material={materials['Material.001']}
                  />
                </group>
              </group>
              <group name="Icosphere001_126" position={[0, -2.021, 0]} scale={0.834}>
                <mesh
                  name="Object_168"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_168.geometry}
                  material={materials['Material.001']}
                />
                <group name="Sphere140_84" position={[0.009, -0.994, -0.006]} scale={0.228}>
                  <mesh
                    name="Object_170"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_170.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere141_85" position={[0.733, -0.44, 0.568]} scale={0.228}>
                  <mesh
                    name="Object_172"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_172.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere142_86" position={[-0.252, -0.457, 0.876]} scale={0.228}>
                  <mesh
                    name="Object_174"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_174.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere143_87" position={[-0.918, -0.451, -0.03]} scale={0.228}>
                  <mesh
                    name="Object_176"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_176.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere144_88" position={[-0.303, -0.465, -0.871]} scale={0.228}>
                  <mesh
                    name="Object_178"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_178.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere145_89" position={[0.698, -0.42, -0.512]} scale={0.228}>
                  <mesh
                    name="Object_180"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_180.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere146_90" position={[0.257, 0.416, 0.845]} scale={0.228}>
                  <mesh
                    name="Object_182"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_182.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere147_91" position={[-0.731, 0.448, 0.519]} scale={0.228}>
                  <mesh
                    name="Object_184"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_184.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere148_92" position={[-0.715, 0.475, -0.517]} scale={0.228}>
                  <mesh
                    name="Object_186"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_186.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere149_93" position={[0.276, 0.442, -0.862]} scale={0.228}>
                  <mesh
                    name="Object_188"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_188.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere150_94" position={[0.906, 0.441, 0.045]} scale={0.228}>
                  <mesh
                    name="Object_190"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_190.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere151_95" position={[0.006, 0.991, 0.002]} scale={0.228}>
                  <mesh
                    name="Object_192"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_192.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere152_96" position={[-0.166, -0.855, 0.497]} scale={0.228}>
                  <mesh
                    name="Object_194"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_194.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere153_97" position={[0.434, -0.85, 0.317]} scale={0.228}>
                  <mesh
                    name="Object_196"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_196.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere154_98" position={[0.254, -0.537, 0.789]} scale={0.228}>
                  <mesh
                    name="Object_198"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_198.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere155_99" position={[0.854, -0.557, 0.024]} scale={0.228}>
                  <mesh
                    name="Object_200"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_200.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere156_100" position={[0.428, -0.871, -0.279]} scale={0.228}>
                  <mesh
                    name="Object_202"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_202.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere157_101" position={[-0.505, -0.844, 0.01]} scale={0.228}>
                  <mesh
                    name="Object_204"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_204.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere158_102" position={[-0.712, -0.515, 0.49]} scale={0.228}>
                  <mesh
                    name="Object_206"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_206.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere159_103" position={[-0.184, -0.846, -0.476]} scale={0.228}>
                  <mesh
                    name="Object_208"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_208.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere160_104" position={[-0.672, -0.519, -0.519]} scale={0.228}>
                  <mesh
                    name="Object_210"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_210.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere161_105" position={[0.231, -0.56, -0.82]} scale={0.228}>
                  <mesh
                    name="Object_212"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_212.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere162_106" position={[0.946, 0.018, 0.302]} scale={0.228}>
                  <mesh
                    name="Object_214"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_214.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere163_107" position={[0.964, -0.018, -0.305]} scale={0.228}>
                  <mesh
                    name="Object_216"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_216.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere164_108" position={[0.032, 0.007, 1.036]} scale={0.228}>
                  <mesh
                    name="Object_218"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_218.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere165_109" position={[0.584, 0.01, 0.815]} scale={0.228}>
                  <mesh
                    name="Object_220"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_220.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere166_110" position={[-0.948, 0.007, 0.31]} scale={0.228}>
                  <mesh
                    name="Object_222"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_222.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere167_111" position={[-0.617, 0.025, 0.823]} scale={0.228}>
                  <mesh
                    name="Object_224"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_224.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere168_112" position={[-0.594, 0.017, -0.806]} scale={0.228}>
                  <mesh
                    name="Object_226"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_226.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere169_113" position={[-0.93, -0.006, -0.298]} scale={0.228}>
                  <mesh
                    name="Object_228"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_228.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere170_114" position={[0.587, 0.003, -0.804]} scale={0.228}>
                  <mesh
                    name="Object_230"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_230.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere171_115" position={[-0.02, -0.005, -0.976]} scale={0.228}>
                  <mesh
                    name="Object_232"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_232.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere172_116" position={[0.707, 0.492, 0.494]} scale={0.228}>
                  <mesh
                    name="Object_234"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_234.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere173_117" position={[-0.237, 0.542, 0.784]} scale={0.228}>
                  <mesh
                    name="Object_236"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_236.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere174_118" position={[-0.854, 0.51, 0.009]} scale={0.228}>
                  <mesh
                    name="Object_238"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_238.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere175_119" position={[-0.256, 0.536, -0.827]} scale={0.228}>
                  <mesh
                    name="Object_240"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_240.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere176_120" position={[0.693, 0.518, -0.492]} scale={0.228}>
                  <mesh
                    name="Object_242"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_242.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere177_121" position={[0.135, 0.84, 0.505]} scale={0.228}>
                  <mesh
                    name="Object_244"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_244.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere178_122" position={[0.523, 0.837, 0.02]} scale={0.228}>
                  <mesh
                    name="Object_246"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_246.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere179_123" position={[-0.43, 0.852, 0.308]} scale={0.228}>
                  <mesh
                    name="Object_248"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_248.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere180_124" position={[-0.397, 0.875, -0.338]} scale={0.228}>
                  <mesh
                    name="Object_250"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_250.geometry}
                    material={materials['Material.001']}
                  />
                </group>
                <group name="Sphere181_125" position={[0.166, 0.851, -0.495]} scale={0.228}>
                  <mesh
                    name="Object_252"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_252.geometry}
                    material={materials['Material.001']}
                  />
                </group>
              </group>
              <group name="Sphere001_127" position={[0, -2.021, 0]} scale={0.19}>
                <mesh
                  name="Object_254"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_254.geometry}
                  material={materials['Material.001']}
                />
              </group>
              <group name="Sphere002_134" position={[4.808, -2.063, -1.342]} scale={0.151}>
                <mesh
                  name="Object_256"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_256.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere003_135" position={[4.465, -4.113, -0.884]} scale={0.151}>
                <mesh
                  name="Object_258"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_258.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere004_137" position={[1.252, -2.063, 4.833]} scale={0.151}>
                <mesh
                  name="Object_260"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_260.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere005_138" position={[0.691, -2.38, 4.934]} scale={0.151}>
                <mesh
                  name="Object_262"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_262.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere006_139" position={[-4.848, -2.063, 1.191]} scale={0.151}>
                <mesh
                  name="Object_264"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_264.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere007_140" position={[-4.492, -0.001, 0.698]} scale={0.151}>
                <mesh
                  name="Object_266"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_266.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere008_141" position={[-1.282, -2.063, -4.825]} scale={0.151}>
                <mesh
                  name="Object_268"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_268.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere009_142" position={[-0.747, -1.72, -4.924]} scale={0.151}>
                <mesh
                  name="Object_270"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_270.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere010_143" position={[0.012, -6.05, -1.167]} scale={0.151}>
                <mesh
                  name="Object_272"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_272.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere011_144" position={[0.012, -6.156, -0.71]} scale={0.151}>
                <mesh
                  name="Object_274"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere012_145" position={[0.003, -3.18, 4.002]} scale={0.151}>
                <mesh
                  name="Object_276"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_276.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere013_146" position={[0.002, -2.67, 4.11]} scale={0.151}>
                <mesh
                  name="Object_278"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_278.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere014_147" position={[-0.012, 1.978, 0.966]} scale={0.151}>
                <mesh
                  name="Object_280"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere015_148" position={[-0.012, 2.054, 0.555]} scale={0.151}>
                <mesh
                  name="Object_282"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_282.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere016_149" position={[-0.003, -1.021, -4.022]} scale={0.151}>
                <mesh
                  name="Object_284"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_284.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere017_150" position={[-0.002, -1.404, -4.102]} scale={0.151}>
                <mesh
                  name="Object_286"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_286.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere018_151" position={[-0.006, -0.162, 3.694]} scale={0.151}>
                <mesh
                  name="Object_288"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_288.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere019_152" position={[-0.007, 0.177, 3.498]} scale={0.151}>
                <mesh
                  name="Object_290"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_290.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere020_153" position={[-0.01, 1.435, -2.24]} scale={0.151}>
                <mesh
                  name="Object_292"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_292.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere021_154" position={[-0.01, 1.143, -2.641]} scale={0.151}>
                <mesh
                  name="Object_294"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_294.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere022_155" position={[0.009, -5.224, -2.694]} scale={0.151}>
                <mesh
                  name="Object_296"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_296.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere023_156" position={[0.01, -5.479, -2.363]} scale={0.151}>
                <mesh
                  name="Object_298"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_298.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere024_157" position={[0.011, -5.63, 2.129]} scale={0.151}>
                <mesh
                  name="Object_300"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_300.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere025_158" position={[0.01, -5.35, 2.539]} scale={0.151}>
                <mesh
                  name="Object_302"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_302.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere026_159" position={[4.105, -2.063, -2.84]} scale={0.151}>
                <mesh
                  name="Object_304"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_304.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere027_160" position={[0.002, -2.782, -4.092]} scale={0.151}>
                <mesh
                  name="Object_306"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_306.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere028_161" position={[0.003, -3.189, -3.999]} scale={0.151}>
                <mesh
                  name="Object_308"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_308.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere029_162" position={[-2.562, -3.254, -1.76]} scale={0.151}>
                <mesh
                  name="Object_310"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_310.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere030_163" position={[0, -1.678, 0]} scale={0.151}>
                <mesh
                  name="Object_312"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_312.geometry}
                  material={materials['Material.003']}
                />
              </group>
              <group name="Sphere031_164" position={[-2.293, -3.129, -2.164]} scale={0.151}>
                <mesh
                  name="Object_314"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_314.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere032_165" position={[-0.866, -2.466, -3.189]} scale={0.151}>
                <mesh
                  name="Object_316"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_316.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere033_166" position={[-0.422, -2.259, -3.296]} scale={0.151}>
                <mesh
                  name="Object_318"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_318.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere034_167" position={[0.41, -1.872, -3.298]} scale={0.151}>
                <mesh
                  name="Object_320"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_320.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere035_168" position={[0.854, -1.666, -3.193]} scale={0.151}>
                <mesh
                  name="Object_322"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_322.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere036_169" position={[2.221, -1.03, -2.253]} scale={0.151}>
                <mesh
                  name="Object_324"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_324.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere037_170" position={[2.503, -0.899, -1.859]} scale={0.151}>
                <mesh
                  name="Object_326"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_326.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere038_171" position={[2.88, -0.723, -0.995]} scale={0.151}>
                <mesh
                  name="Object_328"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_328.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere039_172" position={[2.983, -0.676, -0.507]} scale={0.151}>
                <mesh
                  name="Object_330"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_330.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere040_173" position={[2.601, -0.853, 1.688]} scale={0.151}>
                <mesh
                  name="Object_332"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_332.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere041_174" position={[2.341, -0.974, 2.1]} scale={0.151}>
                <mesh
                  name="Object_334"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_334.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere042_175" position={[0.83, -1.677, 3.201]} scale={0.151}>
                <mesh
                  name="Object_336"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_336.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere043_176" position={[0.385, -1.884, 3.302]} scale={0.151}>
                <mesh
                  name="Object_338"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_338.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere044_177" position={[-1.279, -2.658, 3.015]} scale={0.151}>
                <mesh
                  name="Object_340"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_340.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere045_178" position={[-1.675, -2.842, 2.768]} scale={0.151}>
                <mesh
                  name="Object_342"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_342.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere046_179" position={[-2.907, -3.415, 0.895]} scale={0.151}>
                <mesh
                  name="Object_344"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_344.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere047_180" position={[-2.996, -3.456, 0.403]} scale={0.151}>
                <mesh
                  name="Object_346"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_346.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere048_181" position={[-2.003, -0.688, 0.639]} scale={0.151}>
                <mesh
                  name="Object_348"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_348.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere049_182" position={[-2.07, -0.642, 0.179]} scale={0.151}>
                <mesh
                  name="Object_350"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_350.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere050_183" position={[-0.617, -1.642, -2.346]} scale={0.151}>
                <mesh
                  name="Object_352"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_352.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere051_184" position={[-0.241, -1.9, -2.448]} scale={0.151}>
                <mesh
                  name="Object_354"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_354.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere054_185" position={[1.882, -3.355, -0.831]} scale={0.151}>
                <mesh
                  name="Object_356"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_356.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere055_186" position={[1.976, -3.42, -0.378]} scale={0.151}>
                <mesh
                  name="Object_358"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_358.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere056_187" position={[0.553, -2.443, 2.373]} scale={0.151}>
                <mesh
                  name="Object_360"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_360.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere057_188" position={[0.176, -2.184, 2.468]} scale={0.151}>
                <mesh
                  name="Object_362"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_362.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere058_189" position={[1.624, -2.063, -0.256]} scale={0.151}>
                <mesh
                  name="Object_364"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_364.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere059_190" position={[1.459, -2.063, -0.767]} scale={0.151}>
                <mesh
                  name="Object_366"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_366.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere060_191" position={[4.523, 1.215, -1.141]} scale={0.151}>
                <mesh
                  name="Object_368"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_368.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="Sphere061_192" position={[4.408, 1.131, -1.709]} scale={0.151}>
                <mesh
                  name="Object_370"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_370.geometry}
                  material={materials['Material.002']}
                />
              </group>
              <group name="BezierCircle007_195" position={[0, -2.063, 0]} scale={1.682}>
                <mesh
                  name="Object_372"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_372.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="BezierCircle008_196"
                position={[0, -2.063, 0]}
                rotation={[0, 0, -0.602]}
                scale={2.483}>
                <mesh
                  name="Object_374"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_374.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="BezierCircle009_197"
                position={[0, -2.063, 0]}
                rotation={[0, 0, 0.435]}
                scale={3.329}>
                <mesh
                  name="Object_376"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_376.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="BezierCircle010_198"
                position={[0, -2.063, 0]}
                rotation={[0, 0, -1.568]}
                scale={4.154}>
                <mesh
                  name="Object_378"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_378.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group name="BezierCircle011_199" position={[0, -2.063, 0]} scale={4.992}>
                <mesh
                  name="Object_380"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_380.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="BezierCircle012_200"
                position={[0, -2.063, 0]}
                rotation={[0, 0, 0.627]}
                scale={5.831}>
                <mesh
                  name="Object_382"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_382.geometry}
                  material={materials['Material.005']}
                />
              </group>
              <group
                name="BezierCircle013_201"
                position={[0, -2.063, 0]}
                rotation={[0, 0, -0.43]}
                scale={4.992}>
                <mesh
                  name="Object_384"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_384.geometry}
                  material={materials['Material.005']}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
